version: "3.8"
services:
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   image: backend-service
  #   container_name: dxid-backend-service
  #   restart: unless-stopped
  #   networks:
  #     - dxid-services-net
  #   env_file: .env
  #   ports:
  #     - 5000:5000
  #   depends_on:
  #     - db
  #     - redis

  db:
    image: postgres:17-alpine
    container_name: dxid-db-service
    restart: always
    networks:
      - dxid-services-net
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      PGDATA: /var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: dxid-pgadmin-service
    restart: always
    networks:
      - dxid-services-net
    environment:
      PGADMIN_DEFAULT_EMAIL: $PG_USER_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PG_PASSWORD
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
  
  redis:
    image: redis:latest
    container_name: dxid-redis-service
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    restart: always
    networks:
      - dxid-services-net
    ports:
      - "6380:6379"
    command: ["redis-server"]
  
  redisinsight:
    image: redis/redisinsight:latest
    container_name: dxid-redisinsight
    restart: always
    ports:
      - 5540:5540
    volumes:
      - redisinsight:/data
    networks:
      - dxid-services-net

volumes:
  postgres-data:
  pgadmin-data:
  redisinsight:

networks:
  dxid-services-net:
    name: dxid-services-net
      